@HyperCheeseConstants = 
  PayloadSources:
    SERVER_ACTION: "SERVER_ACTION",
    VIEW_ACTION: "VIEW_ACTION" 

  ActionTypes: 
    REQUEST_SEARCH: "REQUEST_SEARCH"
    REQUEST_SEARCH_SUCCESS: "REQUEST_SEARCH_SUCCESS"
    REQUEST_SEARCH_COMPLETE: "REQUEST_SEARCH_COMPLETE"

    UPDATE_ITEM: "UPDATE_ITEM"



